### ISSUE TITLE
Loading DeepSeek-Coder-V2-Instruct using transformers fails due to OOM on 8 * A100 (80GB)

### ISSUE THREAD

**Issue by dhaneshsabane** [deepseek-ai/DeepSeek-Coder-V2#30]
As the recommended [VLLM approach fails](#29) to load the model, I tried using the transformers approach. However, this fails too due to OutOfMemoryError -

```
Traceback (most recent call last):
  File "/workspace/deepseek/test.py", line 4, in <module>
    model = AutoModelForCausalLM.from_pretrained("deepseek-ai/DeepSeek-Coder-V2-Instruct", trust_remote_code=True, torch_dtype=torch.bfloat16, device_map="balanced_low_0").cuda()
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 559, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3904, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/big_modeling.py", line 419, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 655, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 655, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 655, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 615, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 160, in add_hook_to_module
    module = hook.init_hook(module)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 282, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device, tied_params_map=self.tied_params_map)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/modeling.py", line 396, in set_module_tensor_to_device
    new_value = old_value.to(device)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 7 has a total capacity of 79.14 GiB of which 12.75 MiB is free. Process 9327 has 79.12 GiB memory in use. Of the allocated memory 78.70 GiB is allocated by PyTorch, and 8.95 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

Setting `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` as suggested also doesn't help.

Further, I tried to install accelerate and use the `device_map` parameter, but this approach also fails with the following error message:

```
Some parameters are on the meta device device because they were offloaded to the cpu.
You shouldn't move a model that is dispatched using accelerate hooks.
Traceback (most recent call last):
  File "/workspace/deepseek/test.py", line 4, in <module>
    model = AutoModelForCausalLM.from_pretrained("deepseek-ai/DeepSeek-Coder-V2-Instruct", trust_remote_code=True, torch_dtype=torch.bfloat16, device_map="balanced_low_0").cuda()
  File "/usr/local/lib/python3.10/dist-packages/accelerate/big_modeling.py", line 455, in wrapper
    raise RuntimeError("You can't move a model that has some modules offloaded to cpu or disk.")
RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.
```

Am I doing something wrong here? Can someone please direct me here?

**Comment by viktara** [comment]
+1

**Comment by SupercarryNg** [comment]
same situation on 8*A800

**Comment by zhangfan-algo** [comment]
same situation on 8*A800

**Comment by apotheque** [comment]
to use this model on 8 GPUs with VLLM you have to set --tensor-parallel-size 8. I don't know why they set it to 1 in the example, because it literally means to put all tensors on a single GPU

**Comment by dhaneshsabane** [comment]
@apotheque - You're right. However, setting the parameter to 8 was also resulting in failures when I raised the issue.

The latest version of vLLM at the time of writing - `0.5.3.post1` - is now able to load the model.
